apiVersion: v1
kind: Secret
metadata:
  name: subman-secrets
  namespace: subman
type: Opaque
stringData:
  # PLAIN TEXT ONLY. Do not use Base64 here.
  DB_PASSWORD: "YourPassword123!"

  # PLAIN TEXT URL.
  # format: postgresql://subman_user:YourPassword123!@postgres-headless.subman:5432/subman_db
  DATABASE_URL: "postgresql://subman_user:YourPassword123!@postgres-headless.subman:5432/subman_db"
