apiVersion: v1
kind: Secret
metadata:
  name: subman-secrets
  namespace: subman
type: Opaque
stringData:
  # PLAIN TEXT ONLY. Do not use Base64 here.
  DB_PASSWORD: "YourPassword123!"

  # PLAIN TEXT URL.
  # format: postgresql://subman_user:YourPassword123!@postgres-headless.subman:5432/subman_db
  DATABASE_URL: "postgresql://subman_user:YourPassword123!@postgres-headless.subman:5432/subman_db"
data:
  # Paste the long Base64 strings here
  # Database & Auth
  SUPABASE_URL: aHR0cHM6Ly96ZmNnbmZma29hbm10cnRsdnBoaS5zdXBhYmFzZS5jbw==
  SUPABASE_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5wbVkyZHVabVpyYjJGdWJYUnlkR3gyY0docElpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTmpZME1UTXhNREVzSW1WNGNDSTZNakE0TVRrNE9URXdNWDAuZ2FaTlRYbS1QVTc0VTU3c1ZKMFM2TmpnZG5iNEdyVzE2dWZXa3Z4QXFMWQ==
  SUPABASE_SERVICE_ROLE_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5wbVkyZHVabVpyYjJGdWJYUnlkR3gyY0docElpd2ljbTlzWlNJNkluTmxjblpwWTJWZmNtOXNaU0lzSW1saGRDSTZNVGMyTmpReE16RXdNU3dpWlhod0lqb3lNRGd4T1RnNU1UQXhmUS5RMFpfX1dNTmU1MmlRZEVxVFhQRzN5RnJnNWZNTkNEck1LajhzUTZRX3Aw
  #  Email (SMTP) Settings
  SMTP_HOST: c210cC5nbWFpbC5jb20=
  SMTP_PORT: NTg3
  SMTP_USER: ai5zaGVmZmVyNzQ3QGdtYWlsLmNvbQ==
  SMTP_PASSWORD: dmFjZGlkcXZlb3huampieg==
  SMTP_FROM: U3VibWFuIChqLnNoZWZmZXI3NDdAZ21haWwuY29tKQ==
