apiVersion: apps/v1
kind: Deployment
metadata:
  name: subman-api
  namespace: subman
spec:
  template:
    spec:
      containers:
      - name: subman-api
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subman-client
  namespace: subman
spec:
  template:
    spec:
      containers:
      - name: subman-client
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"