apiVersion: v1
kind: Service
metadata:
  name: subman-api
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: subman-api
  ports:
    - port: 3000
      targetPort: 3000
