apiVersion: apps/v1
kind: Deployment
metadata:
  name: subman-client
  namespace: {{ .Release.Namespace }}
  labels:
    app: subman-client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: subman-client
  template:
    metadata:
      labels:
        app: subman-client
    spec:
      containers:
      - name: subman-client
        image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
        imagePullPolicy: {{ .Values.client.image.pullPolicy }}
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20