apiVersion: v1
kind: ConfigMap
metadata:
  name: subman-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.api.service.port | quote }}
  POSTGRES_DB: {{ .Values.postgres.dbName | quote }}
  POSTGRES_USER: {{ .Values.postgres.dbUser | quote }}
  DB_HOST: "postgres-headless"
