apiVersion: v1
kind: Service
metadata:
  name: postgres-headless # Matches DB_HOST in your ConfigMap
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
spec:
  clusterIP: None # <--- This makes it "Headless"
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres
