apiVersion: apps/v1
kind: Deployment
metadata:
  name: subman-api
  namespace: subman
spec:
  template:
    spec:
      containers:
      - name: subman-api
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readinessz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5