apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-stateful
  namespace: subman
spec:
  template:
    spec:
      containers:
      - name: postgres
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 5
          periodSeconds: 5